"""Tests for the rendering engine — the linguistic core (§6).

Fixture data is hand-copied from `data/verbs_irregular.csv` and
`data/verbs_regular.csv`, reshaped into the *bare*, ingestion-normalised form
the domain layer actually sees (§5): separable verbs store forms with the
prefix stripped — e.g. uufhänke's CSV participle `uufghänkt` becomes the bare
`ghänkt` plus `separable_prefix="uuf"`. Regular verbs' present forms are
generated by `expand_regular` at ingestion time (§13, out of scope for this
milestone), so they're spelled out here by hand following the class-A rule
(stem + `-e/-sch/-t/-ed`, grammar_rules.md §1): `mache` -> stem `mach`,
`uufhänke` -> strip prefix, stem `hänk`.

`ha.present_sg3` is taken verbatim from the seed CSV (`het` — the owner resolved
the §17 "hät vs het" open item by storing the "common variant" `het`); this
suite locks in whatever the seed currently says.
"""

from __future__ import annotations

import pytest

from app.domain.enums import Person, Tense
from app.domain.models import Verb, VerbForms
from app.domain.rendering import AuxiliaryForms, render

# --- Auxiliaries (data/verbs_irregular.csv rows 1 `si`, 2 `ha`, 26 `werde`)

HAA = Verb(
    id=2,
    infinitive="ha",
    english_gloss="to have",
    frequency_rank=2,
    aux="ha",
    has_konjunktiv2=True,
    is_auxiliary=True,
)
HAA_FORMS = VerbForms(
    verb_id=2,
    present_sg1="han",
    present_sg2="häsch",
    present_sg3="het",
    present_pl="händ",
    participle="gha",
    konj2_sg1="hätt",
    konj2_sg2="hättsch",
    konj2_sg3="hätt",
    konj2_pl="hätted",
)

SII = Verb(
    id=1,
    infinitive="si",
    english_gloss="to be",
    frequency_rank=1,
    aux="si",
    has_konjunktiv2=True,
    is_auxiliary=True,
)
SII_FORMS = VerbForms(
    verb_id=1,
    present_sg1="bin",
    present_sg2="bisch",
    present_sg3="isch",
    present_pl="sind",
    participle="gsi",
    konj2_sg1="wär",
    konj2_sg2="wärsch",
    konj2_sg3="wär",
    konj2_pl="wäred",
)

WERDE = Verb(
    id=26,
    infinitive="werde",
    english_gloss="to become / future aux",
    frequency_rank=26,
    aux="si",
    has_konjunktiv2=True,
    is_auxiliary=True,
)
WERDE_FORMS = VerbForms(
    verb_id=26,
    present_sg1="wird",
    present_sg2="wirsch",
    present_sg3="wird",
    present_pl="wèèrded",
    participle="woorde",
    konj2_sg1="wüürd",
    konj2_sg2="wüürdsch",
    konj2_sg3="wüürd",
    konj2_pl="wèèrded",
)

AUX = AuxiliaryForms(haa=HAA_FORMS, sii=SII_FORMS, werde=WERDE_FORMS)


# --- Other irregulars (data/verbs_irregular.csv rows 6 `wele`, 15 `choo`) ----

CHOO = Verb(
    id=15,
    infinitive="choo",
    english_gloss="to come",
    frequency_rank=15,
    aux="si",
    has_konjunktiv2=False,
)
CHOO_FORMS = VerbForms(
    verb_id=15,
    present_sg1="chume",
    present_sg2="chunsch",
    present_sg3="chunt",
    present_pl="chömed",
    participle="choo",
)

WELE = Verb(
    id=6,
    infinitive="wele",
    english_gloss="to want",
    frequency_rank=6,
    aux="ha",
    has_konjunktiv2=True,
)
WELE_FORMS = VerbForms(
    verb_id=6,
    present_sg1="wott",
    present_sg2="wottsch",
    present_sg3="wott",
    present_pl="wänd",
    participle="wele",
    konj2_sg1="wett",
    konj2_sg2="wettsch",
    konj2_sg3="wett",
    konj2_pl="wetted",
)


# --- Regular verbs (data/verbs_regular.csv rows id 124 `mache`, 141 `uufhänke`)

MACHE = Verb(
    id=124,
    infinitive="mache",
    english_gloss="to do",
    frequency_rank=100,
    aux="ha",
    verb_class="A",
)
MACHE_FORMS = VerbForms(
    verb_id=124,
    present_sg1="mache",
    present_sg2="machsch",
    present_sg3="macht",
    present_pl="mached",
    participle="gmacht",
)

UUFHAENKE = Verb(
    id=141,
    infinitive="uufhänke",
    english_gloss="to hang up",
    frequency_rank=117,
    aux="ha",
    verb_class="A",
    separable_prefix="uuf",
)
UUFHAENKE_FORMS = VerbForms(
    verb_id=141,
    present_sg1="hänke",
    present_sg2="hänksch",
    present_sg3="hänkt",
    present_pl="hänked",
    participle="ghänkt",
)


# --- §6: "a regular class-A verb: mache (ha, non-separable) in all four tenses"


def test_mache_present():
    assert render(MACHE, MACHE_FORMS, Tense.PRESENT, Person.SG3, AUX) == "er macht"


def test_mache_perfect():
    assert render(MACHE, MACHE_FORMS, Tense.PERFECT, Person.SG3, AUX) == "er het gmacht"


def test_mache_future():
    assert render(MACHE, MACHE_FORMS, Tense.FUTURE, Person.SG3, AUX) == "er wird mache"


def test_mache_konjunktiv2_slot_does_not_exist():
    # mache isn't one of the six KII verbs (grammar_rules.md §6) -> the konj2
    # slot doesn't exist; card_gen must not emit it, and render must refuse (§6).
    assert MACHE.has_konjunktiv2 is False
    with pytest.raises(ValueError):
        render(MACHE, MACHE_FORMS, Tense.KONJ2, Person.SG3, AUX)


# --- §6: "a separable verb: uufhänke (ha, prefix uuf) — present, perfect, future"


def test_uufhaenke_present_detaches_prefix_to_clause_end():
    assert render(UUFHAENKE, UUFHAENKE_FORMS, Tense.PRESENT, Person.SG3, AUX) == "er hänkt uuf"


def test_uufhaenke_perfect_reattaches_prefix_to_participle():
    assert render(UUFHAENKE, UUFHAENKE_FORMS, Tense.PERFECT, Person.SG3, AUX) == "er het uufghänkt"


def test_uufhaenke_future_keeps_infinitive_attached():
    assert render(UUFHAENKE, UUFHAENKE_FORMS, Tense.FUTURE, Person.SG3, AUX) == "er wird uufhänke"


# --- §6: "perfect with si: choo (si) — er isch choo" -------------------------


def test_choo_perfect_uses_si_auxiliary():
    assert render(CHOO, CHOO_FORMS, Tense.PERFECT, Person.SG3, AUX) == "er isch choo"


# --- §6: "KII: ha -> er hätt, si -> er wär, wele -> er wett" -----------------


def test_konjunktiv2_ha():
    assert render(HAA, HAA_FORMS, Tense.KONJ2, Person.SG3, AUX) == "er hätt"


def test_konjunktiv2_si():
    assert render(SII, SII_FORMS, Tense.KONJ2, Person.SG3, AUX) == "er wär"


def test_konjunktiv2_wele():
    assert render(WELE, WELE_FORMS, Tense.KONJ2, Person.SG3, AUX) == "er wett"


# --- §6: "future of werde itself (edge case): er wird werde" ----------------


def test_werde_future_of_itself():
    assert render(WERDE, WERDE_FORMS, Tense.FUTURE, Person.SG3, AUX) == "er wird werde"


# --- §6: override hook — a pre-assembled string bypasses rule-based assembly -


def test_override_hook_bypasses_assembly_for_that_cell_only():
    overridden = VerbForms(
        verb_id=141,
        present_sg1="hänke",
        present_sg2="hänksch",
        present_sg3="hänkt",
        present_pl="hänked",
        participle="ghänkt",
        overrides={(Tense.PRESENT, Person.SG3): "er hänkt grad uuf"},
    )

    assert render(UUFHAENKE, overridden, Tense.PRESENT, Person.SG3, AUX) == "er hänkt grad uuf"
    # Cells without an override still fall through to rule-based assembly.
    assert render(UUFHAENKE, overridden, Tense.FUTURE, Person.SG3, AUX) == "er wird uufhänke"


# --- pronouns/persons beyond sg3, spot-checked across all four tenses --------


@pytest.mark.parametrize(
    ("person", "expected"),
    [
        (Person.SG1, "ich mache"),
        (Person.SG2, "du machsch"),
        (Person.SG3, "er macht"),
        (Person.PL, "mir mached"),
    ],
)
def test_present_renders_every_person(person: Person, expected: str):
    assert render(MACHE, MACHE_FORMS, Tense.PRESENT, person, AUX) == expected
