"""add per-profile tense toggles and verb enablement

Revision ID: 2b3736d8eeca
Revises: dea04f003fdf
Create Date: 2026-06-08 01:16:05.599507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3736d8eeca'
down_revision: Union[str, Sequence[str], None] = 'dea04f003fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verb_enablement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('verb_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['verb_id'], ['verbs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'verb_id')
    )
    op.create_index(op.f('ix_verb_enablement_profile_id'), 'verb_enablement', ['profile_id'], unique=False)
    op.create_index(op.f('ix_verb_enablement_verb_id'), 'verb_enablement', ['verb_id'], unique=False)
    # server_default=true so existing profile rows backfill to "everything on"
    # (matches the ORM column default — nobody loses tenses they were drilling).
    op.add_column(
        'profiles',
        sa.Column('tense_present_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        'profiles',
        sa.Column('tense_perfect_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        'profiles',
        sa.Column('tense_future_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        'profiles',
        sa.Column('tense_konj2_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'tense_konj2_enabled')
    op.drop_column('profiles', 'tense_future_enabled')
    op.drop_column('profiles', 'tense_perfect_enabled')
    op.drop_column('profiles', 'tense_present_enabled')
    op.drop_index(op.f('ix_verb_enablement_verb_id'), table_name='verb_enablement')
    op.drop_index(op.f('ix_verb_enablement_profile_id'), table_name='verb_enablement')
    op.drop_table('verb_enablement')
    # ### end Alembic commands ###
