"""baseline schema

Revision ID: dea04f003fdf
Revises: 
Create Date: 2026-06-07 23:18:15.048636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea04f003fdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('infinitive', sa.String(), nullable=False),
    sa.Column('english_gloss', sa.String(), nullable=False),
    sa.Column('frequency_rank', sa.Integer(), nullable=False),
    sa.Column('verb_class', sa.String(), nullable=True),
    sa.Column('separable_prefix', sa.String(), nullable=True),
    sa.Column('aux', sa.String(), nullable=False),
    sa.Column('has_konjunktiv2', sa.Boolean(), nullable=False),
    sa.Column('is_auxiliary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verbs_frequency_rank'), 'verbs', ['frequency_rank'], unique=False)
    op.create_index(op.f('ix_verbs_infinitive'), 'verbs', ['infinitive'], unique=True)
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('card_key', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_log_profile_id'), 'review_log', ['profile_id'], unique=False)
    op.create_table('review_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('card_key', sa.String(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('last_reviewed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'card_key')
    )
    op.create_index(op.f('ix_review_state_due_date'), 'review_state', ['due_date'], unique=False)
    op.create_index(op.f('ix_review_state_profile_id'), 'review_state', ['profile_id'], unique=False)
    op.create_table('verb_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb_id', sa.Integer(), nullable=False),
    sa.Column('form_key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['verb_id'], ['verbs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verb_id', 'form_key')
    )
    op.create_index(op.f('ix_verb_forms_verb_id'), 'verb_forms', ['verb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verb_forms_verb_id'), table_name='verb_forms')
    op.drop_table('verb_forms')
    op.drop_index(op.f('ix_review_state_profile_id'), table_name='review_state')
    op.drop_index(op.f('ix_review_state_due_date'), table_name='review_state')
    op.drop_table('review_state')
    op.drop_index(op.f('ix_review_log_profile_id'), table_name='review_log')
    op.drop_table('review_log')
    op.drop_index(op.f('ix_verbs_infinitive'), table_name='verbs')
    op.drop_index(op.f('ix_verbs_frequency_rank'), table_name='verbs')
    op.drop_table('verbs')
    op.drop_table('profiles')
    # ### end Alembic commands ###
